#cloud-config

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install minimal required packages
packages:
  - git
  - curl

# Run commands on first boot
runcmd:
  - git clone https://github.com/band-40/hosted-cloud-core.git /tmp/hosted-cloud-core
  - chmod +x /tmp/hosted-cloud-core/install-cloud-core.sh
  - /tmp/hosted-cloud-core/install-cloud-core.sh > /var/log/cloud-core-install.log 2>&1 