#cloud-config

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install minimal required packages
packages:
  - git
  - curl

# Create a user
users:
  - name: epcuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

# Run commands on first boot
runcmd:
  - git clone https://github.com/band-40/hosted-cloud-core.git /tmp/hosted-cloud-core
  - chmod +x /tmp/hosted-cloud-core/install-open5gs.sh
  - /tmp/hosted-cloud-core/install-open5gs.sh > /var/log/open5gs-install.log 2>&1 